// <auto-generated />
namespace Monthley.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AnythingNew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnythingNew));
        
        string IMigrationMetadata.Id
        {
            get { return "202105131549092_AnythingNew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
